defaults:
  - task_config_base
  - measurements:
    - distance_to_goal
    - distance_to_goal_reward
    - multi_agent_nav_reward # for falcon
    - success 
    - did_multi_agents_collide 
    - num_steps 
    - top_down_map
    - spl
    - psc
    - stl
    - human_collision
    - human_future_trajectory # for falcon
  - lab_sensors:
    - localization_sensor 
    - human_num_sensor # for falcon
    - oracle_humanoid_future_trajectory # for falcon
  - _self_

type: MultiAgentPointNavTask-v0
end_on_success: True
reward_measure: "multi_agent_nav_reward"
success_measure: "success"
success_reward: 12.0 # 原10.0修改为12.0
slack_reward: -0.002
goal_sensor_uuid: pointgoal_with_gps_compass
measurements:
  multi_agent_nav_reward:
    type: MultiAgentNavReward
    use_geo_distance: true
    allow_distance: 3.0 # 原2.0修改为3.0
    collide_scene_penalty: -0.02 # 原-0.005修改为-0.02
    collide_human_penalty: -0.08 # 原-0.015修改为-0.08
    close_to_human_penalty: -0.008 # 原-0.003修改为-0.008
    trajectory_cover_penalty: -0.002 # 原-0.0005修改为-0.002
    cover_future_dis_thre: 0.1 # 原0.05修改为0.1
    robot_idx: 0
    facing_human_dis: 3.0 # 原2.0修改为3.0